--- #YAML:1.0
name: Math-Symbolic-Custom-ErrorPropagation
version: 0.10
abstract: Calculate Gaussian Error Propagation
license: perl
distribution_type: module
requires:
  Test::More: 0.44
  Math::Symbolic: 0.132
dynamic_config: 0
